// Seed script for populating the food database with common Ayurvedic foods

import { foodDatabaseService } from './firestore';

export const seedFoodDatabase = async () => {
  const sampleFoods = [
    // Vegetables
    {
      name: "Spinach (Palak)",
      category: "Vegetable" as const,
      nutritionalData: {
        calories: 23,
        protein: 2.9,
        carbohydrates: 3.6,
        fat: 0.4,
        fiber: 2.2,
        sodium: 79,
        potassium: 558,
        calcium: 99,
        iron: 2.7,
        vitaminC: 28.1,
        vitaminA: 9377,
      },
      ayurvedicProperties: {
        rasa: ["Sweet", "Bitter"],
        virya: "Cold",
        guna: ["Light", "Dry"],
        vipaka: "Sweet",
        doshaEffect: ["Vata-pacifying", "Pitta-pacifying"],
        digestibility: "Easy",
        potency: "Mild",
      },
      commonAlternatives: [],
      regionalVariations: ["Palak", "Cheera"],
    },
    {
      name: "Bitter Gourd (Karela)",
      category: "Vegetable" as const,
      nutritionalData: {
        calories: 17,
        protein: 1.0,
        carbohydrates: 3.0,
        fat: 0.2,
        fiber: 2.6,
        sodium: 5,
        potassium: 296,
        calcium: 19,
        iron: 0.4,
        vitaminC: 84,
        vitaminA: 471,
      },
      ayurvedicProperties: {
        rasa: ["Bitter"],
        virya: "Cold",
        guna: ["Light", "Dry"],
        vipaka: "Pungent",
        doshaEffect: ["Pitta-pacifying", "Kapha-pacifying"],
        digestibility: "Moderate",
        potency: "Strong",
      },
      commonAlternatives: [],
      regionalVariations: ["Karela", "Pavakkai"],
    },
    {
      name: "Fenugreek Leaves (Methi)",
      category: "Vegetable" as const,
      nutritionalData: {
        calories: 49,
        protein: 4.4,
        carbohydrates: 6.2,
        fat: 0.9,
        fiber: 2.7,
        sodium: 67,
        potassium: 770,
        calcium: 395,
        iron: 6.2,
        vitaminC: 52,
        vitaminA: 8400,
      },
      ayurvedicProperties: {
        rasa: ["Bitter"],
        virya: "Hot",
        guna: ["Light", "Dry"],
        vipaka: "Pungent",
        doshaEffect: ["Vata-pacifying", "Kapha-pacifying"],
        digestibility: "Moderate",
        potency: "Strong",
      },
      commonAlternatives: [],
      regionalVariations: ["Methi", "Menthi Kura"],
    },

    // Fruits
    {
      name: "Indian Gooseberry (Amla)",
      category: "Fruit" as const,
      nutritionalData: {
        calories: 44,
        protein: 0.9,
        carbohydrates: 10.2,
        fat: 0.6,
        fiber: 4.3,
        sodium: 1,
        potassium: 198,
        calcium: 25,
        iron: 0.3,
        vitaminC: 478.9,
        vitaminA: 6,
      },
      ayurvedicProperties: {
        rasa: ["Sour", "Sweet", "Astringent", "Pungent"],
        virya: "Cold",
        guna: ["Light", "Dry"],
        vipaka: "Sweet",
        doshaEffect: ["Pitta-pacifying", "Tridoshic"],
        digestibility: "Easy",
        potency: "Strong",
      },
      commonAlternatives: [],
      regionalVariations: ["Amla", "Nellikai"],
    },
    {
      name: "Pomegranate (Anar)",
      category: "Fruit" as const,
      nutritionalData: {
        calories: 83,
        protein: 1.7,
        carbohydrates: 18.7,
        fat: 1.2,
        fiber: 4.0,
        sodium: 3,
        potassium: 236,
        calcium: 10,
        iron: 0.3,
        vitaminC: 10.2,
        vitaminA: 0,
      },
      ayurvedicProperties: {
        rasa: ["Sweet", "Sour", "Astringent"],
        virya: "Cold",
        guna: ["Heavy"],
        vipaka: "Sweet",
        doshaEffect: ["Pitta-pacifying", "Vata-aggravating"],
        digestibility: "Moderate",
        potency: "Mild",
      },
      commonAlternatives: [],
      regionalVariations: ["Anar", "Maadhulai"],
    },

    // Grains
    {
      name: "Brown Rice",
      category: "Grain" as const,
      nutritionalData: {
        calories: 111,
        protein: 2.6,
        carbohydrates: 23.0,
        fat: 0.9,
        fiber: 1.8,
        sodium: 4,
        potassium: 86,
        calcium: 10,
        iron: 0.6,
        vitaminC: 0,
        vitaminA: 0,
      },
      ayurvedicProperties: {
        rasa: ["Sweet"],
        virya: "Cold",
        guna: ["Heavy"],
        vipaka: "Sweet",
        doshaEffect: ["Vata-pacifying", "Pitta-aggravating"],
        digestibility: "Moderate",
        potency: "Mild",
      },
      commonAlternatives: [],
      regionalVariations: ["Brown Rice", "Godhumai"],
    },
    {
      name: "Quinoa",
      category: "Grain" as const,
      nutritionalData: {
        calories: 120,
        protein: 4.4,
        carbohydrates: 21.3,
        fat: 1.9,
        fiber: 2.8,
        sodium: 5,
        potassium: 172,
        calcium: 17,
        iron: 1.5,
        vitaminC: 0,
        vitaminA: 0,
      },
      ayurvedicProperties: {
        rasa: ["Sweet"],
        virya: "Cold",
        guna: ["Light"],
        vipaka: "Sweet",
        doshaEffect: ["Vata-pacifying", "Tridoshic"],
        digestibility: "Easy",
        potency: "Mild",
      },
      commonAlternatives: [],
      regionalVariations: ["Quinoa"],
    },

    // Dairy
    {
      name: "Cow's Milk (Organic)",
      category: "Dairy" as const,
      nutritionalData: {
        calories: 61,
        protein: 3.2,
        carbohydrates: 4.8,
        fat: 3.3,
        fiber: 0,
        sodium: 43,
        potassium: 132,
        calcium: 113,
        iron: 0.0,
        vitaminC: 0,
        vitaminA: 46,
      },
      ayurvedicProperties: {
        rasa: ["Sweet"],
        virya: "Cold",
        guna: ["Heavy", "Oily"],
        vipaka: "Sweet",
        doshaEffect: ["Vata-pacifying", "Pitta-aggravating"],
        digestibility: "Moderate",
        potency: "Mild",
      },
      commonAlternatives: [],
      regionalVariations: ["Cow Milk", "Pasu Payasam"],
    },

    // Spices
    {
      name: "Turmeric (Haldi)",
      category: "Spice" as const,
      nutritionalData: {
        calories: 354,
        protein: 9.7,
        carbohydrates: 64.9,
        fat: 3.3,
        fiber: 21.1,
        sodium: 27,
        potassium: 2525,
        calcium: 183,
        iron: 41.4,
        vitaminC: 0.7,
        vitaminA: 0,
      },
      ayurvedicProperties: {
        rasa: ["Bitter", "Pungent"],
        virya: "Hot",
        guna: ["Light", "Dry"],
        vipaka: "Pungent",
        doshaEffect: ["Kapha-pacifying", "Tridoshic"],
        digestibility: "Easy",
        potency: "Strong",
      },
      commonAlternatives: [],
      regionalVariations: ["Haldi", "Manjal"],
    },
    {
      name: "Cumin Seeds (Jeera)",
      category: "Spice" as const,
      nutritionalData: {
        calories: 375,
        protein: 17.8,
        carbohydrates: 44.2,
        fat: 22.3,
        fiber: 10.5,
        sodium: 168,
        potassium: 1788,
        calcium: 931,
        iron: 66.4,
        vitaminC: 7.7,
        vitaminA: 64,
      },
      ayurvedicProperties: {
        rasa: ["Bitter", "Pungent"],
        virya: "Hot",
        guna: ["Light", "Dry"],
        vipaka: "Pungent",
        doshaEffect: ["Vata-pacifying", "Kapha-pacifying"],
        digestibility: "Easy",
        potency: "Strong",
      },
      commonAlternatives: [],
      regionalVariations: ["Jeera", "Jeeragam"],
    },

    // Oils
    {
      name: "Coconut Oil",
      category: "Oil" as const,
      nutritionalData: {
        calories: 862,
        protein: 0,
        carbohydrates: 0,
        fat: 100,
        fiber: 0,
        sodium: 0,
        potassium: 0,
        calcium: 0,
        iron: 0,
        vitaminC: 0,
        vitaminA: 0,
      },
      ayurvedicProperties: {
        rasa: ["Sweet"],
        virya: "Cold",
        guna: ["Heavy", "Oily"],
        vipaka: "Sweet",
        doshaEffect: ["Vata-pacifying", "Pitta-aggravating"],
        digestibility: "Difficult",
        potency: "Mild",
      },
      commonAlternatives: [],
      regionalVariations: ["Coconut Oil", "Tengai Ennai"],
    },
    {
      name: "Ghee (Clarified Butter)",
      category: "Oil" as const,
      nutritionalData: {
        calories: 876,
        protein: 0.3,
        carbohydrates: 0.1,
        fat: 99.5,
        fiber: 0,
        sodium: 2,
        potassium: 5,
        calcium: 4,
        iron: 0.0,
        vitaminC: 0,
        vitaminA: 653,
      },
      ayurvedicProperties: {
        rasa: ["Sweet"],
        virya: "Hot",
        guna: ["Heavy", "Oily"],
        vipaka: "Sweet",
        doshaEffect: ["Vata-pacifying", "Pitta-aggravating"],
        digestibility: "Moderate",
        potency: "Mild",
      },
      commonAlternatives: [],
      regionalVariations: ["Ghee", "Neyi"],
    },
  ];

  try {
    console.log('Seeding food database...');
    const promises = sampleFoods.map(food => {
      const { createdAt, updatedAt, ...foodData } = food;
      return foodDatabaseService.create(foodData);
    });
    await Promise.all(promises);
    console.log(`Successfully seeded ${sampleFoods.length} foods into the database`);
    return true;
  } catch (error) {
    console.error('Error seeding food database:', error);
    return false;
  }
};

// Export for use in components
export default seedFoodDatabase;